### ISSUE TITLE
Show heatmap when a movie is selected 

### ISSUE THREAD

**Issue by kaplanlior** [linnovate/replay-api#101]

**Comment by bora89** [comment]
Can you describe that a little bit more?

**Comment by kaplanlior** [comment]
When a movie is selected from the query results (or by the timeline), so the heatmap of on top of the movie's trace in the map. See wireframe 12 (English version).

**Comment by bora89** [comment]
![](http://joxi.ru/XEA4BlMHqGDjmb?d=1)

**Comment by bora89** [comment]
Moshe's answer: we are speaking about areas from the same movie. so if the movie stays on specific place more time it will have stronger red colour

**Comment by CodeJjang** [comment]
@oldwisenir is working on a convex hull feature which result should be retrieved from server to client in order to efficiently present the heatmap's polygons

**Comment by liran100** [comment]
currently postponed
