### ISSUE TITLE
Verify UI search work without hardcoded parts

### ISSUE THREAD

**Issue by kaplanlior** [linnovate/replay-api#102]

**Comment by bora89** [comment]
[![UI demo](https://i.ytimg.com/vi_webp/nRRJgxEwo7k/maxresdefault.webp)](http://www.youtube.com/embed/nRRJgxEwo7k?vq=hd1080 "UI demo")

The only thing is that, I can not load manifest file from your server, I wrote Moshe - he said it worked for him. But for me: ![](http://joxi.ru/Y82Q9wdtbbQE2d?d=1)

**Comment by bora89** [comment]
Does not work: http://vod.linnovate.net:1935/weplay/_definst_/kaltura_content/20160728/0/0_ervwr6f7_0_83qjoyd1_2.mp4/manifest.mpd
