### ISSUE TITLE
Implement playlists in the UI

### ISSUE THREAD

**Issue by kaplanlior** [linnovate/replay-api#103]

**Comment by bora89** [comment]
![](http://joxi.ru/wRmzG7WFZZ9D2O?d=1)
![](http://joxi.ru/qVrwvkOtddlEAX?d=1)

**Comment by bora89** [comment]
Is that enough?

**Comment by kaplanlior** [comment]
What about the playlist tab in the UI (see wireframe on page 2) which incl. a few default playlists?

**Comment by bora89** [comment]
I suppose they are not default, but created by user. So UI should provide tools for managin playlists, like for example on youtube: ![](http://joxi.ru/QeAO9wVtnqxwmo?d=1)
