### ISSUE TITLE
Adjust MetadataToCaptions service to RMQ

### ISSUE THREAD

**Issue by CodeJjang** [linnovate/replay-api#119]
& Few bug fixes:
1. Line #64 (And in the rest of the service): You assume all metadatas are of the same video? But that depends on the standard. I think that would also change the baseDate calculations you do there.
2. Line #74: Check if getTimeDiff returns null?
3. Please write comments on all the C-like code there in createCaptions function...

**Comment by moshesharon** [comment]
1. _You assume all metadatas are of the same video?_ **YES!**  
We think that separation should be in early stages in the processing-services.  
@CodeJjang Your opinion?

**Comment by moshesharon** [comment]
2. Done (throw Error and handle catch...)

**Comment by kaplanlior** [comment]
Well done for the closing issues syntax.
