### ISSUE TITLE
Clean Up ffmpeg

### ISSUE THREAD

**Issue by dinzone** [linnovate/replay-api#120]
ffmpeg doesn't clean up when killing it from the node process, need to find out why, and how to fix it.

**Comment by kaplanlior** [comment]
Clean up files, clean up processes?

**Comment by dinzone** [comment]
find out why it is happen, the mp4 format not support on cleaning the video before ffmpeg process stop, 
but the pmeg-ts format do, now that i found out what the problem we need to add some logic after every section of video (when it done the half hour or when there is no streaming), working on it right now.
