### ISSUE TITLE
add to mongo the time of video finish

### ISSUE THREAD

**Issue by liran100** [linnovate/replay-api#123]
add to mongo the time we finish capture the video.
1. add this time in the finish capture and send it to capture
2. change the schema on queue - change\add work of relevent consumer
3. save to mongo

**Comment by dinzone** [comment]
just now added the feature to the video-recorder module...

**Comment by dinzone** [comment]
I checked both options, the duration of the video compared to the filewatcher, and what I saw is that the duration is more accurately, anyway I reduced the time trial of the filewatcher to second half to be more realtime, so actually succeed to interrupting videos when there pause in the streaming, I checked this change and saw it more accurate and enable to work properly.
