### ISSUE TITLE
Decouple authorization-ui and several more authorization related issues

### ISSUE THREAD

**Issue by CodeJjang** [linnovate/replay-api#185]
- Separate authorization-ui to authorization-ui & authorization-service, and move the ui to replay-api.
- Extract the cron job from authorization-ui to a separate service authorization-cron-job.
- Extract the `generateCompartmentCondition` function from VideoCompartment to a controller in authorization-service:
  1. The controller will receive the userCode (perhaps a better name is needed here... userProviderId?) and return the user permissions as a JSON array.
  2. The VideoCompartment method generateCompartmentCondition will receive the user permissions and return a condition to add to a mongo query.

**Comment by CodeJjang** [comment]
Finished the cron job bullet.

**Comment by nirklinger** [comment]
`generateCompartmentCondition` DONE
authorization service (including mongo query and compartment mock)DONE
