### ISSUE TITLE
Debugging Sails env

### ISSUE THREAD

**Issue by oldwisenir** [linnovate/replay-api#33]
Learn how to debug your env

**Comment by motyros** [comment]
Just use [Node Inspector...](https://github.com/node-inspector/node-inspector)
(Also compatible with Sails and mocha)

**Comment by motyros** [comment]
@oldwisenir please give me a feedback on how is it debugging in visual code.

**Comment by dinzone** [comment]
@motyros i think node inspector is pretty good.

**Comment by motyros** [comment]
@dinzone I know... 
But I still want @oldwisenir to try out a little to t debug in visual code, just to know if it worth it...

**Comment by moshesharon** [comment]
looks nice

**Comment by liran100** [comment]
@motyros  please present this ability.
move to close!
