### ISSUE TITLE
Complete API for UI searches

### ISSUE THREAD

**Issue by kaplanlior** [linnovate/replay-api#96]
Please specify each added API here.

**Comment by CodeJjang** [comment]
Update:
I've completed most of the searches available on the UI: Search video between two dates;
Search video between two durations in seconds;
Search video by source (/sourceId);
Search video by tags;

Also now it is possible to add tags to specific video, and retrieve all tags available in the app.

What's left is to work on the query by minimum polygon size & duration of the drone inside the bounding polygon.

**Comment by kaplanlior** [comment]
@bora89 - FYI about @CodeJjang progress.

**Comment by CodeJjang** [comment]
Finished everything except the limitation of the polygons intersection size (e.g. 200x200), postponed this feature as it may require unexpected effort to accomplish.
